Prefix: '&f[&ePlayerInv&f] '

Language: 'en-US'

Voucher:
  large:
    material: PAPER
    enchant-glow: true
    custom-model-data: 0
  medium:
    material: PAPER
    enchant-glow: true
    custom-model-data: 0
  Sound: true
  Value: 'UI_TOAST_CHALLENGE_COMPLETE:1:1'
  Title: true

## Customize vault amount
Vault:
  Large_amount: 30
  Medium_amount: 30

## player use command: /inv keys toggle to disabled/enabled to toggle F function
OpenToggle: true

GUI:
  Sound_value: 'UI_BUTTON_CLICK:1:2'

## use F function to open main menu
KeysOpen: true
Need-sneaking: true

OpenGUIMessage: true

Inventory:
  Blacklist:
    - 'BARRIER'

Luckperms-proxy-support: false
Sync-server:
  - 'lobby'
  - 'sc'
  - 'zy'

DataBases:
  MySQL: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: playerinv
  allowPublicKeyRetrieval: false