Prefix: '&f[&ePlayerInv&f] '

Language: 'en-US'

Debug-mode: false

check-update: true

## Voucher settings
## 兑换券物品设置
Voucher:
  large:
    material: PAPER
    enchant-glow: true
    custom-model-data: 0
  medium:
    material: PAPER
    enchant-glow: true
    custom-model-data: 0
  Sound: true
  Value: 'UI_TOAST_CHALLENGE_COMPLETE:1:1'
  Title: true
  Set-owner : true

## Customize vault amount
## 自定义仓库数量
Vault:
  Large_amount: 30
  Medium_amount: 30

## player use command: /inv keys toggle to disabled/enabled to toggle F function
OpenToggle: true

GUI:
  Sound_value: 'UI_BUTTON_CLICK:1:2'
  Vault_open: 'ENTITY_EXPERIENCE_ORB_PICKUP:0.8:1.1'

## use F function to open main menu
KeysOpen: true
Need-sneaking: true

OpenGUIMessage: true

Inventory:
  Blacklist:
    - 'BARRIER'

## Return to the main menu when closing the vault GUI
## 是否启用 当关闭仓库菜单时返回主菜单
## 玩家可通过/inv return toggle 控制
Return-to-main:
  Enabled: true

## When the player has the permission playerinv.death.store
## Can store dropped items in the vault when player death
##
## By default, it will detect whether the player's world has enabled GameRules: keepInventory
##
## When ignore-keepInventory enabled, If the item still falls after death
## These items will still be stored in the vault
##----------------------
## 当玩家拥有权限: playerinv.death.store
## 玩家死亡后 物品会存储到大型仓库中
##
## 默认会检测玩家所在世界是否开启游戏规则: 死亡不掉落
##
## 若 ignore-keepInventory 开启, 如果物品仍然在死亡后掉落
## 这些物品仍会被收纳至仓库
Player-death-store:
  Enabled: false
  ignore-keepInventory: false

## The plugin will use the Luckperms API to give permissions
## Please ensure that Luckperms is installed
## Only applicable to giving permissions within a single server
## Using for permission expiry or not
##
## If multiple server permissions are required, please enable Luckperms-proxy-support
##------------------------
## 开启后 插件将会使用 Luckperms API进行权限给予
## 请确保 Luckperms 已经安装
## 开启后将适用于单服务端的权限给予以及限时权限给予
##
## 如果需要用到多服务端权限同步 请开启 Luckperms-proxy-support
Luckperms-give-permissions: false

## Only applicable for multi server using BungeeCord or Velocity
## Not available for single server
## If single server using it, it cannot give permission when using vouchers and commands
##
## Please make sure Luckperms-give-permissions was enabled.
##-------------------
## 仅适用于多服务端的代理情况下 如BungeeCord或Velocity
## 不适用于单服务端
## 若单服务端开启 将无法通过兑换券和指令给予权限
## 使用前请确保 Luckperms-give-permissions 开启
Luckperms-proxy-support: false
Sync-server:
  - 'lobby'
  - 'sc'
  - 'zy'

DataBases:
  MySQL: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: playerinv
  allowPublicKeyRetrieval: false
  useSSL: true