name: PlayerInv
version: '${version}'
main: com.playerinv.PlayerInv
api-version: '1.14'
folia-supported: true
commands:
  playerinv:
    aliases: inv
permissions:
  playerinv.admin:
    default: op
  playerinv.check:
    default: false
  playerinv.reload:
    default: false
  playerinv.inv.*:
    default: false
  playerinv.keys.toggle:
    default: true
  playerinv.give:
    default: false
  playerinv.gui.open:
    default: true
  playerinv.invsort:
    default: true
  playerinv.invopen:
    default: true

depend: [Vault]
softdepend: [LuckPerms]
