name: PlayerInv
version: '${version}'
main: com.playerinv.PlayerInv
api-version: '1.14'
folia-supported: true
commands:
  playerinv:
    aliases: inv
permissions:
  playerinv.admin:
    default: op
  playerinv.check:
    default: op
  playerinv.reload:
    default: op
  playerinv.inv.*:
    default: false
  playerinv.keys.toggle:
    default: true
  playerinv.give:
    default: op
  playerinv.gui.open:
    default: true
  playerinv.invsort:
    default: true
  playerinv.invopen:
    default: true
  playerinv.large.inv.*:
    default: op
  playerinv.medium.inv.*:
    default: op
  playerinv.vault.give:
    default: op
  playerinv.vault.append:
    default: op
  playerinv.death.store:
    default: false
  playerinv.return.toggle:
    default: true
  playerinv.blacklist.material.ignore:
    default: false
  playerinv.blacklist.lore.ignore:
    default: false
  playerinv.enderchest.open:
    default: false

depend: [Vault]
softdepend:
  - PlaceholderAPI
  - Luckperms
